-- Create email_history table
create table if not exists email_history (
  id bigint generated by default as identity primary key,
  purpose text not null,
  tone text not null,
  email_text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies
alter table email_history enable row level security;

-- Create policy to allow inserts
create policy "Allow inserts for all users" on email_history
  for insert with check (true);

-- Create policy to allow users to view their own history
create policy "Allow users to view their own history" on email_history
  for select using (true); 